
  const films = [
    {
      titre: "TENET",
      duree: "2h15",
      restriction: '+12',
      genre: "Science Fiction-action-thriller-espionnage",
      resolutionmax: "4K",
      synopsis: `Muni d'un seul mot – Tenet – et décidé à se battre pour sauver le monde, notre protagoniste sillonne l'univers crépusculaire de l'espionnage international. Sa mission le projettera dans une dimension qui dépasse le temps. Pourtant, il ne s'agit pas d'un voyage dans le temps, mais d'un renversement temporel…`,
      type: 'Film',
      annee: "2020",
      realisation: "...........",
      distribution: "............................",
      favori: false,
      download:false,
      watchtime: 60,
      view: 100000,
      // suite: "Standalone",
      miniPortrait: "TenetPortrait.jpg",      
      titleIMG:"TenetTitle.png",
      miniPaysage: "TenetPaysage.png"
    },
    {
      titre: "Sinners",
      duree: "2h15",
      restriction: '+12',
      genre: "Science Fiction-action-thriller-espionnage",
      resolutionmax: "4K",
      synopsis: `Alors qu’ils cherchent à s’affranchir d’un lourd passé, deux frères jumeaux reviennent dans leur ville natale pour repartir à zéro. Mais ils comprennent qu’une puissance maléfique bien plus redoutable guette leur retour avec impatience…

« À force de danser avec le diable, un beau jour, il viendra te chercher chez toi. »`,
      type: 'Film',
      annee: "2020",
      realisation: " Ryan Coogler",
      distribution: "............................",
      favori: false,
      download:false,
      watchtime: 0,
      view: 70000,
      // suite:"Film unique",
      miniPortrait: "SinnersPortrait.jpg",
      titleIMG:"SinnersTitle.png",
      miniPaysage: "SinnersPaysage.png"
    },
    {
      titre: "Avengers : Infinity war",
      duree: "2h15",
      restriction: '+12',
      genre: "Science Fiction-action-thriller-espionnage",
      resolutionmax: "4K",
      synopsis: `Les Avengers et leurs alliés devront être prêts à tout sacrifier pour neutraliser le redoutable Thanos avant que son attaque éclair ne conduise à la destruction complète de l’univers.`,
      type: 'Film',
      annee: "2020",
      realisation: "...........",
      distribution: "............................",
      favori: false,
      download:false,
      watchtime: 90,
      view: 800000,
      // suite: "saga",
      miniPortrait: "AvergersinfinitywarPortrait.png",
      titleIMG:"AvergersinfinitywarTitle.png",
      miniPaysage: "AvergersinfinitywarPaysage.png"
    },
    {
      titre: "Shrek",
      duree: "2h15",
      restriction: '+12',
      genre: "Science Fiction-action-thriller-espionnage",
      resolutionmax: "4K",
      synopsis: `Muni d'un seul mot, "Tenet," et décidé à se battre pour sauver le monde...`,
      type: 'Film',
      annee: "2020",
      realisation: "...........",
      distribution: "............................",
      favori: false,
      download:false,
      watchtime: 73,
      view: 500000,
      // suite: "saga",
      miniPortrait: "ShrekPortrait.jpg",      
      titleIMG:"ShrekTitle.png",
      miniPaysage: "ShrekPaysage.jpg"
    },
    {
      titre: "Astérix mission Cléopatre",
      duree: "1h40",
      restriction: '+7',
      genre: "Commedie, Aventure, Film famille, Film jeunesse ",
      resolutionmax: "HD",
      synopsis: `À la demande de Cléopâtre et avec l'aide des Gaulois, Numérobis se lance dans le pari fou d'ériger un palais en 3 mois, tout en déjouant les fourberies d'Amonbofis.`,
      type: 'Film',
      annee: "2002",
      realisation: "Alain chabbat",
      distribution: "gerard Depardieu, Jamel Debbouze, Christian Clavier, Dieudonné",
      favori: true,
      download:true,
      watchtime: 100,
      view: 400000,
      // suite: "saga",
      miniPortrait: "AsterixmissioncleopatrePortrait.jpg",      
      titleIMG:"AsterixmissioncleopatreTitle.png",
      miniPaysage: "AsterixmissioncleopatrePaysage.png"
    },
    
    {
      titre: "Case Depart",
      duree: "1h34",
      restriction: '+12',
      genre: "Comédies, Français",
      resolutionmax: "HD",
      synopsis: `Victimes d'un sort, deux hommes qui n'ont rien en commun à part leur père se retrouvent dans le passé, où l'esclavage existe encore. Pour survivre, ils vont devoir s'entendre..`,
      type: 'Film',
      annee: "2011",
      realisation: "Fabrice Eboué, Thomas Ngijol",
      distribution: "Fabrice Eboué, Thomas Ngijol, Frank Migeon",
      favori: true,
      download:true,
      watchtime: 0,
      view: 500000,
      // suite: "saga",
      miniPortrait: "CasedepartPortrait.jpg",      
      titleIMG:"CasedepartTitle.png",
      miniPaysage: "CasedepartPaysage.jpg"
    },
        {
      titre: "Babylon",
      duree: "3h15",
      restriction: '+12',
      genre: "Drame, Comédie",
      resolutionmax: "4K",
      synopsis: `Hollywood, années 1920, l'industrie est en train de passer du cinéma muet au cinéma parlé. Ce film "Babylon" suit l'ascension et la chute de quelques individus, dont Nellie LaRoy et Jack Conrad, à une époque où la décadence et la dépravation sont omniprésentes dans cette industrie.`,
      type: 'Film',
      annee: "2020",
      realisation: "Damien Chazelle",
      distribution: "Margot Robbie, Diego Calva, Brad Pitt, Tobey Maguire",
      favori: true,
      download:true,
      watchtime: 100,
      view: 600000,
      // suite: "saga",
      miniPortrait: "BabylonPortrait.png",      
      titleIMG:"BabylonTitle.png",
      miniPaysage: "BabylonPaysage.png"
    },
    
    {
      titre: "southpark",
      restriction: '+12',
      genre: "commedie",
      resolutionmax: "HD",
      synopsis: `La petite ville de South Park dans le Colorado est le théâtre des aventures de Cartman, Stan, Kyle et Kenny, quatre enfants qui ont un langage un peu... décalé !`,
      type: 'Serie',
      annee: "2010-225",
      realisation: "...........",
      distribution: "............................",
      favori: false,
      download:false,
      view: 300000,
      saison:[  {
              saison: 1,
              episodes: [
                { titre: "Cartman a une sonde anale", duree: "22min",minia:"ep1S1southpark.png", synopsis:"Les aliens implantent un émetteur dans Cartman et kidnappent le frère de Kyle",watchtime: 98 },
                { titre: "Muscle Plus 4000", duree: "22min",minia:"ep2S1southpark.png", synopsis:"Cartman tente de se muscler en prenant du Muscle Plus 4000. De son côté, M. Garrison essaye d'assassiner Kathie Lee Gifford.",watchtime: 98 },
                { titre: "Volcano", duree: "22min",minia:"ep3S1southpark.png", synopsis:"Les enfants partent à la chasse avec Jimbo, l'oncle de Stan, lorsqu'un volcano entre en éruption. Cartman invente la légende de Kucrapok pour faire peur aux autres mais est-ce seulement imaginaire ?",watchtime: 98},
                { titre: "	Une promenade complètement folle avec Al Super Gay", duree: "22min",minia:"ep4S1southpark.png", synopsis:"Les enfants cherchent à faire un croisement entre un éléphant et un cochon de lait.",watchtime: 98},
                { titre: "Un éléphant fait l'amour à un cochon", duree: "22min",minia:"ep5S1southpark.png", synopsis:"Les enfants cherchent à faire un croisement entre un éléphant et un cochon de lait." },
                { titre: "La Mort", duree: "22min",minia:"ep6S1southpark.png", synopsis:"Marvin Marsh, le grand père de Stan, veut absolument mourir. Il demande à son petit-fils de l'aider.",watchtime: 98 },
                { titre: "Conjonctivite", duree: "22min",minia:"ep7S1southpark.png", synopsis:"Les aliens implantent un émetteur dans Cartman et kidnappent le frère de Kyle",watchtime: 50 },
                { titre: "Le Petit Éthernopien", duree: "22min",minia:"ep8S1southpark.png", synopsis:"Pensant recevoir une montre à quartz, les enfants envoient cinq dollars en Éthiopie, mais ils reçoivent en fait un enfant du pays.",watchtime: 0 },
                { titre: "Monsieur Hankey, le petit caca Noël",minia:"ep9S1southpark.png", duree: "22min", synopsis:"Noël approche et les enfants préparent un spectacle sur la naissance de Jésus. Mais voilà qui ne plait pas aux parents de Kyle, dont la famille est juive.",watchtime: 0 },
                { titre: "Damien", duree: "22min",minia:"ep10S1southpark.png", synopsis:"Damien, le fils de Satan, arrive à South Park où son père et Jesus s'apprêtent à livrer bataille.",watchtime: 0 },
                { titre: "La mère de Cartman est une folle du cul",minia:"ep11S1southpark.png", duree: "22min", synopsis:"Cartman ignore qui est son père. Alphonse Mephisto veut bien l'aider, mais les recherches coûtent 3000 $.",watchtime: 0 }
              ]
            },
            {
              saison: 2,
              episodes: [
                { titre: "Le charmeur de poules", duree: "22min",minia:"ep1S2southpark.png", synopsis:"Le bibliobus arrive à South Park. Les enfants n'en ont cure, jusqu'à ce qu'une affaire de viol de poules n'éclate.",watchtime: 0 },
                { titre: "Les Gnomes voleurs de slips", duree: "22min",minia:"ep2S2southpark.png",synopsis:"Mr. Tweek risque de perdre son café à cause de la concurrence des cafés Harbucks.",watchtime: 0 }
              ]
            }
          ],
      // suite: "saga",
      miniPortrait: "SouthparkPortrait.jpg",      
      titleIMG:"SouthparkTitle.png",
      miniPaysage: "SouthparkPaysage.jpg"
    }
  ];
  export default films;

